// Generate item mock data from OpenDota API response
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Chinese name mappings for common items
const chineseNames = {
  // ── Consumables ──
  blink: "闪烁匕首",
  tango: "树之祭祀",
  tango_single: "树之祭祀（共享）",
  flask: "治疗药膏",
  healing_salve: "治疗药膏",
  clarity: "净化药水",
  enchanted_mango: "魔法芒果",
  faerie_fire: "仙灵之火",
  blood_grenade: "血榴弹",
  dust: "显影之尘",
  smoke_of_deceit: "诡计之雾",
  town_portal_scroll: "回城卷轴",
  tpscroll: "回城卷轴",
  ward_observer: "侦查守卫",
  ward_sentry: "岗哨守卫",
  sentry_wards: "岗哨守卫",
  ward_dispenser: "侦查·岗哨守卫",
  aegis: "不朽之守护",
  cheese: "奶酪",
  refresher_shard: "刷新球碎片",
  aghanims_shard: "阿哈利姆魔晶",
  aghanims_blessing: "阿哈利姆福佑",
  ultimate_scepter: "阿哈利姆神杖",
  bottle: "魔瓶",
  // ── Basic items (with API key aliases) ──
  branches: "铁树枝干",
  iron_branch: "铁树枝干",
  gauntlets: "力量手套",
  slippers: "敏捷便鞋",
  mantle: "智力斗篷",
  circlet: "贵族圆环",
  belt_of_strength: "力量腰带",
  boots_of_elves: "精灵皮靴",
  robe: "法师长袍",
  ogre_axe: "食人魔之斧",
  blade_of_alacrity: "欢欣之刃",
  staff_of_wizardry: "魔力法杖",
  ring_of_protection: "守护指环",
  ring_of_regen: "治疗指环",
  ring_of_health: "治疗指环",
  sage_mask: "贤者面罩",
  sobi_mask: "贤者面罩",
  boots_of_speed: "速度之靴",
  boots: "速度之靴",
  gloves: "加速手套",
  blades_of_attack: "攻击之爪",
  chainmail: "锁子甲",
  quarterstaff: "短棍",
  helm_of_iron_will: "铁意头盔",
  broadsword: "阔剑",
  claymore: "大剑",
  javelin: "标枪",
  platemail: "板甲",
  hyperstone: "振奋宝石",
  void_stone: "虚无宝石",
  gem: "真视宝石",
  ghost: "幽魂权杖",
  shadow_amulet: "暗影护符",
  morbid_mask: "吸血面具",
  lifesteal: "吸血面具",
  voodoo_mask: "巫毒面具",
  fluffy_hat: "毛帽",
  wind_lace: "风灵之纹",
  cloak: "抗魔斗篷",
  talisman_of_evasion: "闪避护符",
  blitz_knuckles: "闪电指套",
  ultimate_orb: "极限法球",
  stout_shield: "圆盾",
  poor_mans_shield: "穷鬼盾",
  ring_of_aquila: "天鹰之戒",
  quelling_blade: "压制之斧",
  orb_of_venom: "淬毒之珠",
  infused_raindrop: "凝魂之露",
  magic_stick: "魔棒",
  magic_wand: "魔杖",
  soul_ring: "灵魂之戒",
  crown: "王冠",
  diadem: "王冠",
  mithril_hammer: "秘银锤",
  reaver: "掠夺者之斧",
  eagle: "鹰歌弓",
  eaglesong: "鹰歌弓",
  mystic_staff: "神秘法杖",
  demon_edge: "恶魔刀锋",
  relic: "圣者遗物",
  sacred_relic: "圣者遗物",
  ring_of_tarrasque: "恐鳌之戒",
  energy_booster: "能量之球",
  point_booster: "精气之球",
  vitality_booster: "活力之球",
  soul_booster: "灵魂之球",
  tiara_of_selemene: "瑟勒梅涅之冠",
  wizard_hat: "巫师之帽",
  diffusal_blade: "净魂之刃",
  diffusal_blade_2: "净魂之刃",
  // ── Boots ──
  power_treads: "动力鞋",
  phase_boots: "相位鞋",
  arcane_boots: "奥术鞋",
  tranquil_boots: "静谧之靴",
  boots_of_travel: "远行鞋",
  travel_boots: "远行鞋",
  travel_boots_2: "远行鞋II",
  guardian_greaves: "卫士胫甲",
  boots_of_bearing: "统御头盔",
  force_boots: "原力鞋",
  swift_boots: "迅捷之靴",
  // API key aliases for items with non-standard keys
  invis_sword: "影刃",
  bfury: "狂战斧",
  lesser_crit: "水晶剑",
  greater_crit: "代达罗斯之殇",
  gungir: "缚灵索",
  sheepstick: "邪恶镰刀",
  scythe_of_vyse: "邪恶镰刀",
  cyclone: "EUL的神圣法杖",
  euls: "EUL的神圣法杖",
  ancient_janggo: "韧鼓",
  pers: "坚韧球",
  perseverance: "坚韧球",
  oblivion_staff: "遗忘法杖",
  angels_demise: "天命",
  khanda: "天命",
  aether_lens: "以太透镜",
  blight_stone: "枯萎之石",
  orb_of_blight: "枯萎之石",
  orb_of_frost: "冰霜之球",
  orb_of_corrosion: "腐蚀之珠",
  devastator: "圣契",
  parasma: "圣契",
  dagon_2: "达贡之神力",
  dagon_3: "达贡之神力",
  dagon_4: "达贡之神力",
  dagon_5: "达贡之神力",
  necronomicon: "死灵书",
  necronomicon_2: "死灵书",
  necronomicon_3: "死灵书",
  ultimate_scepter_2: "阿哈利姆福佑",
  ultimate_scepter_roshan: "阿哈利姆福佑（肉山）",
  aghanims_blessing: "阿哈利姆福佑",
  mekansm: "梅肯斯姆",
  wraith_pact: "冥魂盟约",
  headdress: "头巾",
  recipe_cyclone: "EUL神圣法杖合成卷轴",
  // ── Early / Mid game items ──
  bracer: "护腕",
  wraith_band: "幽灵系带",
  null_talisman: "空灵挂件",
  falcon_blade: "猎鹰战刃",
  hand_of_midas: "迈达斯之手",
  mask_of_madness: "疯狂面具",
  battle_fury: "狂战斧",
  desolator: "黯灭",
  maelstrom: "漩涡",
  mjollnir: "雷神之锤",
  crystalys: "水晶剑",
  daedalus: "代达罗斯之殇",
  basher: "碎颅锤",
  abyssal_blade: "深渊之刃",
  radiance: "辉耀",
  butterfly: "蝴蝶",
  satanic: "撒旦之邪力",
  skadi: "斯嘉蒂之眼",
  monkey_king_bar: "金箍棒",
  divine_rapier: "圣剑",
  rapier: "圣剑",
  moon_shard: "银月之晶",
  manta: "幻影斧",
  black_king_bar: "黑皇杖",
  silver_edge: "白银之锋",
  shadow_blade: "影刃",
  echo_sabre: "回音战刃",
  harpoon: "鱼叉",
  nullifier: "否决坠饰",
  disperser: "分散机",
  diffusal_blade: "净魂之刃",
  ethereal_blade: "虚灵之刃",
  dagon: "达贡之神力",
  orchid: "紫怨",
  bloodthorn: "血棘",
  mage_slayer: "巫师之刃",
  witch_blade: "巫师之刃",
  revenants_brooch: "亡魂胸针",
  parasma: "圣契",
  gleipnir: "缚灵索",
  rod_of_atos: "阿托斯之棍",
  dragon_lance: "魔龙枪",
  hurricane_pike: "飓风长戟",
  meteor_hammer: "陨星锤",
  phylactery: "灵匣",
  khanda: "天命",
  armlet: "莫尔迪基安的臂章",
  armlet_of_mordiggian: "莫尔迪基安的臂章",
  // ── Defensive / Utility ──
  hood_of_defiance: "挑战头巾",
  pipe: "洞察烟斗",
  pipe_of_insight: "洞察烟斗",
  eternal_shroud: "永世法衣",
  vanguard: "先锋盾",
  crimson_guard: "赤红甲",
  blade_mail: "刃甲",
  heart: "恐鳌之心",
  tarrasque: "恐鳌之心",
  assault: "强袭胸甲",
  assault_cuirass: "强袭胸甲",
  shivas_guard: "希瓦的守护",
  lotus_orb: "清莲宝珠",
  sphere: "林肯法球",
  linkens_sphere: "林肯法球",
  bloodstone: "血精石",
  aeon_disk: "永恒之盘",
  force_staff: "原力法杖",
  glimmer_cape: "微光披风",
  holy_locket: "圣洁吊坠",
  mekanism: "梅肯斯姆",
  buckler: "圆盾",
  ring_of_basilius: "圣殿指环",
  heavens_halberd: "天堂之戟",
  solar_crest: "炎阳纹章",
  medallion_of_courage: "勇气勋章",
  urn_of_shadows: "影之灵龛",
  spirit_vessel: "魂之灵龛",
  drum_of_endurance: "韧鼓",
  veil_of_discord: "纷争面纱",
  helm_of_the_dominator: "支配头盔",
  helm_of_the_overlord: "统御头盔",
  vladmir: "弗拉迪米尔的祭品",
  ghost_scepter: "幽魂权杖",
  euls: "EUL的神圣法杖",
  wind_waker: "风之杖",
  scythe_of_vyse: "邪恶镰刀",
  octarine_core: "玲珑心",
  refresher: "刷新球",
  overwhelming_blink: "蛮牛闪现",
  swift_blink: "迅捷闪现",
  arcane_blink: "奥术闪现",
  kaya: "慧光",
  yasha: "夜叉",
  sange: "散华",
  kaya_and_sange: "慧夜对剑",
  yasha_and_kaya: "散慧对剑",
  sange_and_yasha: "散夜对剑",
  trident: "三叉戟",
  // ── New 7.41 items ──
  splintmail: "裂片甲",
  shawl: "披肩",
  chasm_stone: "深渊石",
  essence_distiller: "精华蒸馏器",
  consecrated_wraps: "圣洁裹布",
  crellas_crozier: "克莱拉主教权杖",
  eldwurms_edda: "埃尔德武姆史诗",
  pavise: "圣盾",
  // ── Neutral items (common) ──
  arcane_ring: "奥术指环",
  trusty_shovel: "可靠铁铲",
  paladin_sword: "圣骑士剑",
  dragon_scale: "龙鳞",
  spider_legs: "蜘蛛腿",
  vambrace: "臂甲",
  titan_sliver: "泰坦碎片",
  mind_breaker: "碎心刃",
  stormcrafter: "风暴工匠",
  elven_tunic: "精灵外衣",
  penta_edged_sword: "五锋剑",
  stygian_desolator: "冥灵黯灭",
  prism: "棱镜",
  mechanical_arm: "机械臂",
  enchanted_quiver: "附魔箭袋",
  specialists_array: "专家阵列",
  dagger_of_ristul: "利斯塔匕首",
  orb_of_destruction: "毁灭之球",
  bullwhip: "牛鞭",
  phoenix_ash: "凤凰灰烬",
  possessed_mask: "着魔面具",
  trickster_cloak: "诡计披风",
  ninja_gear: "忍者装备",
  illusionsts_cape: "幻术师披风",
  blighted_spirit: "枯萎之灵",
  timeless_relic: "永恒遗物",
  psychic_headband: "灵心头带",
  book_of_shadows: "暗影之书",
  book_of_the_dead: "亡灵之书",
  force_boots: "原力鞋",
  fallen_sky: "陨落天空",
  philosophers_stone: "贤者之石",
  eye_of_the_vizier: "维齐尔之眼",
  orb_of_corrosion: "腐蚀之珠",
  grandmasters_glaive: "宗师长刃",
  flicker: "闪烁",
  seer_stone: "先见之石",
  bottomless_chalice: "无尽圣杯",
  wand_of_the_brine: "盐水之杖",
  whisper_of_the_dread: "恐惧低语",
  bone_golem: "骨傀儡",
  super_blink: "超级闪烁",
  giant_ring: "巨人之戒",
  apex: "巅峰",
  ballista: "弩炮",
  woodland_striders: "林地行者",
  mirror_shield: "镜盾",
  ex_machina: "机械降神",
  book_of_the_dead_2: "亡灵之书",
  pirate_hat: "海盗帽",
  fairy_treasure: "仙灵宝藏",
  magic_jewel: "魔法宝石",
  flaming_scythe: "火焰镰刀",
  glowcap: "萤光菇",
  forebearer: "先祖",
  red_orb: "红球",
  shrink_ray: "缩小射线",
  satchel: "背包",
  // ── Tokens / Consumable neutral items ──
  tier_1_token: "一级中立代币",
  tier_2_token: "二级中立代币",
  tier_3_token: "三级中立代币",
  tier_4_token: "四级中立代币",
  tier_5_token: "五级中立代币",
  // ── Misc / Removed / Seasonal ──
  courier: "动物信使",
  flying_courier: "飞行信使",
  tome_of_knowledge: "知识之书",
  royal_jelly: "皇家蜂蜜",
  mango_tree: "芒果果树",
  repair_kit: "修理包",
  iron_talon: "铁爪",
  // ── Recipes ──
  recipe: "合成卷轴",
  recipe_arcane_blink: "奥术闪现合成卷轴",
  recipe_swift_blink: "迅捷闪现合成卷轴",
  recipe_overwhelming_blink: "蛮牛闪现合成卷轴",
  recipe_magic_wand: "魔杖合成卷轴",
  recipe_travel_boots: "远行鞋合成卷轴",
  recipe_mekansm: "梅肯斯姆合成卷轴",
  recipe_buckler: "圆盾合成卷轴",
  recipe_ring_of_basilius: "圣殿指环合成卷轴",
  recipe_holy_locket: "圣洁吊坠合成卷轴",
  recipe_pipe: "洞察烟斗合成卷轴",
  recipe_urn_of_shadows: "影之灵龛合成卷轴",
  recipe_headdress: "头巾合成卷轴",
  recipe_scythe_of_vyse: "邪恶镰刀合成卷轴",
  recipe_orchid: "紫怨合成卷轴",
  recipe_bloodthorn: "血棘合成卷轴",
  recipe_euls: "EUL神圣法杖合成卷轴",
  recipe_wind_waker: "风之杖合成卷轴",
  recipe_aether_lens: "以太透镜合成卷轴",
  recipe_force_staff: "原力法杖合成卷轴",
  recipe_hurricane_pike: "飓风长戟合成卷轴",
  recipe_dagon: "达贡之神力合成卷轴",
  recipe_aghanims_blessing: "阿哈利姆福佑合成卷轴",
  recipe_refresher: "刷新球合成卷轴",
  recipe_assault: "强袭胸甲合成卷轴",
  recipe_heart: "恐鳌之心合成卷轴",
  recipe_black_king_bar: "黑皇杖合成卷轴",
  recipe_shivas_guard: "希瓦守护合成卷轴",
  recipe_sphere: "林肯法球合成卷轴",
  recipe_lotus_orb: "清莲宝珠合成卷轴",
  recipe_meteor_hammer: "陨星锤合成卷轴",
  recipe_aeon_disk: "永恒之盘合成卷轴",
  recipe_kaya: "慧光合成卷轴",
  recipe_spirit_vessel: "魂之灵龛合成卷轴",
  recipe_essence_distiller: "精华蒸馏器合成卷轴",
  recipe_crimson_guard: "赤红甲合成卷轴",
  recipe_blade_mail: "刃甲合成卷轴",
  recipe_eternal_shroud: "永世法衣合成卷轴",
  recipe_consecrated_wraps: "圣洁裹布合成卷轴",
  recipe_crellas_crozier: "克莱拉权杖合成卷轴",
  recipe_monkey_king_bar: "金箍棒合成卷轴",
  recipe_daedalus: "代达罗斯之殇合成卷轴",
  recipe_basher: "碎颅锤合成卷轴",
  recipe_battle_fury: "狂战斧合成卷轴",
  recipe_manta: "幻影斧合成卷轴",
  recipe_crystalys: "水晶剑合成卷轴",
  recipe_dragon_lance: "魔龙枪合成卷轴",
  recipe_armlet: "臂章合成卷轴",
  recipe_silver_edge: "白银之锋合成卷轴",
  recipe_mjollnir: "雷神之锤合成卷轴",
  recipe_sange: "散华合成卷轴",
  recipe_helm_of_the_dominator: "支配头盔合成卷轴",
  recipe_helm_of_the_overlord: "统御头盔合成卷轴",
  recipe_gleipnir: "缚灵索合成卷轴",
  recipe_yasha: "夜叉合成卷轴",
  recipe_diffusal_blade: "净魂之刃合成卷轴",
  recipe_disperser: "分散机合成卷轴",
  recipe_ethereal_blade: "虚灵之刃合成卷轴",
  recipe_soul_ring: "灵魂之戒合成卷轴",
  recipe_arcane_boots: "奥术鞋合成卷轴",
  recipe_octarine_core: "玲珑心合成卷轴",
  recipe_falcon_blade: "猎鹰战刃合成卷轴",
  recipe_drum: "韧鼓合成卷轴",
  recipe_solar_crest: "炎阳纹章合成卷轴",
  recipe_pavise: "圣盾合成卷轴",
  recipe_veil: "纷争面纱合成卷轴",
  recipe_revenants_brooch: "亡魂胸针合成卷轴",
  recipe_parasma: "圣契合卷轴",
  recipe_guardian_greaves: "卫士胫甲合成卷轴",
  recipe_rod_of_atos: "阿托斯之棍合成卷轴",
  recipe_iron_talon: "铁爪合成卷轴",
  recipe_abyssal_blade: "深渊之刃合成卷轴",
  recipe_heavens_halberd: "天堂之戟合成卷轴",
  recipe_glimmer_cape: "微光披风合成卷轴",
  recipe_harpoon: "鱼叉合成卷轴",
  recipe_bracer: "护腕合成卷轴",
  recipe_wraith_band: "幽灵系带合成卷轴",
  recipe_null_talisman: "空灵挂件合成卷轴",
  recipe_witch_blade: "巫师之刃合成卷轴",
  recipe_phylactery: "灵匣合成卷轴",
  recipe_khanda: "天命合成卷轴",
  // ── Neutral items newer ──
  vengeances_shadow: "复仇之影",
  stygian_desolator: "冥灵黯灭",
  desolator_2: "黯灭II",
  seer_stone_2: "先见之石II",
  warhammer: "战锤",
  stinger: "毒刺",
  demonedge: "恶魔之刃",
  armor_greaves: "装甲胫甲",
  ancient_persuasion: "远古说服",
  soul_stealing_mask: "噬魂面具",
  fairy_trinket: "仙灵饰物",
  chipped_vest: "破碎背心",
  ocean_heart: "海洋之心",
  broom_handle: "扫帚柄",
  nether_shawl: "冥界披肩",
  essence_ring: "精华指环",
  clumsy_net: "笨拙捕网",
  havoc_hammer: "浩劫之锤",
  magic_lamp: "魔法神灯",
  faded_broach: "褪色胸针",
  minotaur_horn: "牛头人号角",
  the_leveller: "平整者",
  cloak_of_flames: "火焰斗篷",
  ceremonial_robe: "仪式长袍",
  quicksilver_amulet: "水银护符",
  giants_ring: "巨人之戒",
  fairys_trinket: "仙灵饰物",
  ascetics_cap: "苦行者之帽",
  brigands_blade: "强盗之刃",
  witchbane: "破法之刃",
  pig_pole: "猪竿",
  tumblers_toy: "不倒翁玩具",
  fae_grenade: "仙灵手雷",
  seeds_of_serenity: "宁静种子",
  lance_of_pursuit: "追猎长矛",
  occult_bracelet: "神秘手镯",
  ogre_seal_totem: "食人魔海豹图腾",
  defiant_shell: "抗争之壳",
  beloved_memory: "挚爱回忆",
  scrying_shovel: "占卜铲",
  forebearers_fortune: "先祖馈赠",
  mercy_and_grace: "慈悲与恩典",
  vindicators_axe: "复仇者之斧",
  duelist_gloves: "决斗者手套",
  ancient_guardian: "远古守护者",
  safety_bubble: "安全气泡",
  nemesis_curse: "复仇诅咒",
  avianas_feather: "艾维娜之羽",
  unwavering_condition: "坚定状态",
  dandelion_amulet: "蒲公英护符",
  martyrs_plate: "殉道者板甲",
  gossamer_cape: "薄纱披风",
  light_collector: "光之收集者",
  rattlecage: "震响之笼",
  doubloon: "达布隆金币",
  roshans_banner: "肉山旗帜",
  unrelenting_eye: "无情之眼",
  mana_draught: "法力药剂",
  rippers_lash: "撕裂者之鞭",
  crippling_crossbow: "致残弩",
  gale_guard: "狂风护甲",
  gunpowder_gauntlet: "火药护手",
  searing_signet: "灼热印记",
  serrated_shiv: "锯齿小刀",
  pollywog_charm: "蝌蚪护符",
  magnifying_monocle: "放大镜",
  pyrrhic_cloak: "惨胜披风",
  madstone_bundle: "狂石包裹",
  kobold_cup: "狗头人酒杯",
  dormant_curio: "休眠古玩",
  sisters_shroud: "姐妹裹尸布",
  jidi_pollen_bag: "吉迪花粉袋",
  outworld_staff: "异界法杖",
  dezun_bloodrite: "德尊血仪",
  giants_maul: "巨人之槌",
  divine_regalia: "神圣王权",
  disgraced_regalia: "耻辱王权",
  bag_of_gold: "金币袋",
  hydras_breath: "多头蛇吐息",
  weighted_dice: "灌铅骰子",
  ash_legion_shield: "灰烬军团之盾",
  riftshadow_prism: "裂影棱镜",
  metamorphic_mandible: "变形之颚",
  idol_of_screeauk: "斯克里奥克偶像",
  flayers_bota: "剥皮者之靴",
  spellslinger: "法术投掷者",
  prophets_pendulum: "先知摆锤",
  stonefeather_satchel: "石羽背包",
  enchanters_bauble: "附魔师玩物",
  harmonizer: "协调者",
  conjurers_catalyst: "魔术师催化剂",
  foragers_kit: "采集者工具包",
  vital_toadstool: "活力毒菌",
  ironwood_nut: "铁木坚果",
  tomokan_ringcap: "托莫坎环盖",
  partisans_brand: "游击者烙印",
  leviathans_fish: "利维坦之鱼",
  // ── Level-up runes for heroes ──
  black_grimoire: "黑暗魔典",
  gris_gris: "格里斯护符",
  vast: "巨大",
  quickened: "迅捷",
  audacious: "无畏",
  mystical: "神秘",
  alert: "警觉",
  brawny: "强壮",
  tough: "坚韧",
  feverish: "狂热",
  fleetfooted: "疾步",
  crude: "粗糙",
  boundless: "无限",
  wise: "智慧",
  timeless: "永恒",
  greedy: "贪婪",
  vampiric: "吸血",
  keen_eyed: "敏锐",
  evolved: "进化",
  titanic: "泰坦",
  fierce: "凶猛",
  dominant: "支配",
  restorative: "恢复",
  thick: "厚重",
  unleashed: "释放",
  vital: "活力",
  hulking: "巨硕",
  manic: "狂躁",
  nimble: "灵活",
  // ── Healing lotuses & misc ──
  famango: "治疗莲花",
  great_famango: "大型治疗莲花",
  greater_famango: "超级治疗莲花",
  royale_with_cheese: "奶酪块",
  river_vial_chrome: "河水药瓶：铬",
  river_vial_dry: "河水药瓶：干涸",
  river_vial_slime: "河水药瓶：粘液",
  river_vial_oil: "河水药瓶：油",
  river_vial_electrified: "河水药瓶：电化",
  river_vial_potion: "河水药瓶：药剂",
  river_vial_blood: "河水药瓶：血",
  tombstone: "墓碑",
  pocket_tower: "袖珍塔",
  pocket_roshan: "袖珍肉山",
  keen_optic: "锐利之眼",
  grove_bow: "丛林之弓",
  quickening_charm: "加速护符",
  elixir: "灵药",
  vampire_fangs: "吸血鬼獠牙",
  arcanists_armor: "奥术师铠甲",
  blast_rig: "爆破装置",
  craggy_coat: "崎岖外衣",
  greater_faerie_fire: "大型仙灵之火",
  mirror_shield: "镜盾",
  ironwood_tree: "铁木之树",
  pupil_gift: "学徒的馈赠",
  tome_of_aghanim: "阿哈利姆之书",
  third_eye: "第三只眼",
  spell_prism: "法术棱镜",
  princes_knife: "王子之刃",
  witless_shako: "愚者之帽",
  imp_claw: "小鬼之爪",
  telescope: "望远镜",
  helm_of_the_undying: "不朽之盔",
  fusion_rune: "融合符文",
  ocean_heart: "海洋之心",
  spark_of_courage: "勇气火花",
  nether_shawl: "冥界披肩",
  // ── API key aliases (raw API keys → Chinese) ──
  river_painter: "河水药瓶：铬",
  river_painter2: "河水药瓶：干涸",
  river_painter3: "河水药瓶：粘液",
  river_painter4: "河水药瓶：油",
  river_painter5: "河水药瓶：电化",
  river_painter6: "河水药瓶：药剂",
  river_painter7: "河水药瓶：血",
  mutation_tombstone: "墓碑",
  elixer: "灵药",
  black_powder_bag: "爆破装置",
  spy_gadget: "望远镜",
  panic_button: "魔法神灯",
  demonicon: "亡灵之书",
  mysterious_hat: "仙灵饰物",
  heavy_blade: "破法之刃",
  unstable_wand: "猪竿",
  pogo_stick: "不倒翁玩具",
  paintball: "仙灵手雷",
  ofrenda: "挚爱回忆",
  ofrenda_shovel: "占卜铲",
  ofrenda_pledge: "先祖馈赠",
  muertas_gun: "慈悲与恩典",
  gunpowder_gauntlets: "火药护手",
  polliwog_charm: "蝌蚪护符",
  divine_regalia_broken: "耻辱王权",
  furion_gold_bag: "金币袋",
  foragers_health: "活力毒菌",
  foragers_stats: "铁木坚果",
  foragers_mana: "托莫坎环盖",
  tier1_token: "一级中立代币",
  tier2_token: "二级中立代币",
  tier3_token: "三级中立代币",
  tier4_token: "四级中立代币",
  tier5_token: "五级中立代币",
  grisgris: "格里斯护符",
  enhancement_vast: "巨大",
  enhancement_quickened: "迅捷",
  enhancement_audacious: "无畏",
  enhancement_mystical: "神秘",
  enhancement_alert: "警觉",
  enhancement_brawny: "强壮",
  enhancement_tough: "坚韧",
  enhancement_feverish: "狂热",
  enhancement_fleetfooted: "疾步",
  enhancement_crude: "粗糙",
  enhancement_boundless: "无限",
  enhancement_wise: "智慧",
  enhancement_timeless: "永恒",
  enhancement_greedy: "贪婪",
  enhancement_vampiric: "吸血",
  enhancement_keen_eyed: "敏锐",
  enhancement_evolved: "进化",
  enhancement_titanic: "泰坦",
  enhancement_fierce: "凶猛",
  enhancement_dominant: "支配",
  enhancement_restorative: "恢复",
  enhancement_thick: "厚重",
  enhancement_curious: "释放",
  enhancement_vital: "活力",
  enhancement_hulking: "巨硕",
  enhancement_manic: "狂躁",
  enhancement_nimble: "灵活",
  giants_maul: "巨人之槌",
  tidehunter_fish: "利维坦之鱼",
  aghanims_shard_roshan: "阿哈利姆魔晶（消耗品）",
  force_field: "奥术师铠甲",
  pupils_gift: "学徒的馈赠",
  ascetic_cap: "苦行者之帽",
  misericorde: "强盗之刃",
  giant_maul: "巨人之槌",
  cornucopia: "丰饶之角",
  orb_of_blight: "枯萎之球",
  orb_of_frost: "冰霜之球",
  perseverance: "坚韧球",
};

// Item recipes: item ID → array of component item IDs
const itemRecipes = {
  50:  [29, 2, 4],            63:  [29, 25, 17],          180: [29, 59],
  214: [29, 244, 27],         48:  [29, 47],              220: [48, 47],
  36:  [34, 16, 16, 35],      73:  [13, 20, 72],          75:  [14, 20, 74],
  77:  [15, 20, 76],          79:  [94, 86, 78],          231: [79, 180, 230],
  90:  [131, 94, 89],         242: [125, 243],            125: [27, 61, 4],
  131: [31, 27, 93],          94:  [31, 27, 93],
  116: [21, 8, 115],          114: [53, 61, 113],         135: [51, 7, 134],
  141: [149, 51, 144],        149: [3, 2, 148],           208: [143, 61, 207],
  143: [8, 17, 142],          139: [52, 10, 32],          152: [3, 11, 215],
  249: [152, 149, 248],       168: [8, 8, 2],             145: [1125, 3, 5, 64],
  158: [166, 55, 157],        166: [8, 7, 165],
  96:  [58, 24, 57, 105],     108: [60, 21, 22, 23],      110: [69, 69, 109],
  119: [9, 58, 118],          235: [59, 57, 228],         100: [59, 57, 244, 99],
  104: [23, 261, 103],        98:  [67, 67, 69, 97],      250: [98, 55, 245],
  176: [52, 37, 175],         225: [54, 6, 222],
  147: [170, 24, 146],        154: [170, 162],            273: [170, 259],
  277: [162, 259],            170: [22, 18, 169],         162: [21, 17, 161],
  259: [23, 19, 258],         160: [24, 24, 60, 60],      156: [26, 53, 5],
  137: [54, 64],              112: [9, 55, 111],
  102: [27, 101],             263: [102, 236, 262],       236: [21, 17, 234],
  92:  [28, 27, 91],          267: [92, 61, 266],         256: [61, 59, 255],
  123: [24, 69, 122],         226: [69, 9, 221],          206: [23, 23, 261, 205],
  1466:[206, 166, 1565],
  600: [1, 53, 608],          603: [1, 52, 607],          604: [1, 58, 606],
  254: [215, 253],            229: [187, 24, 227],        187: [2, 12, 184],
  269: [94, 61, 268],
  185: [261, 244, 64],        81:  [88, 26, 6, 64],       88:  [12, 28],
  174: [22, 22, 19, 173],     1097:[174, 51, 1096],       151: [6, 2, 150],
  172: [26, 25, 148],         210: [162, 8, 209],         127: [3, 4, 126],
  252: [21, 67, 25],          939: [252, 236, 1101],      596: [261, 2, 25, 599],
  610: [100, 57, 244, 612],   69:  [27, 1125],            178: [27, 28, 177],
  232: [57, 233],             534: [19, 25, 533],
  65:  [25, 64],              223: [27, 28, 57, 222],     106: [23, 17, 105],
  190: [261, 67, 189],        692: [131, 27, 691],        164: [6, 261, 163],
  635: [164, 24, 633],
  1107:[23, 27, 1106],        1808:[1107, 1802, 1805],    911: [598, 88, 910],
  1806:[190, 24, 1805],       1128:[88, 6, 1127],         1852:[92, 79, 1851],
  1856:[261, 67, 1855],       1854:[94, 131, 1853],
};

// Chinese functional descriptions (what the item DOES)
const itemDescriptions = {
  1: "使用后瞬间传送至目标地点（1200范围）。受到来自敌方英雄的伤害后3秒内无法使用。",
  29: "提高移动速度。",
  2: "提高9点攻击力。",
  3: "提高18点攻击力。",
  4: "提高4点护甲。",
  5: "提高20点攻击力。",
  6: "提高6点护甲和5点生命恢复。",
  7: "普通攻击有30%概率额外造成70点魔法伤害。",
  8: "提高24点攻击力。",
  9: "提高10点护甲。",
  10: "提高10点攻击力和10点攻击速度。",
  11: "近战提高18点攻击力，远程提高8点攻击力。可以砍树（4秒CD）。",
  12: "提高3点护甲。",
  13: "提高3点力量。",
  14: "提高3点敏捷。",
  15: "提高3点智力。",
  16: "全属性+1。",
  17: "提高6点力量。",
  18: "提高6点敏捷。",
  19: "提高6点智力。",
  20: "全属性+2。",
  21: "提高10点力量。",
  22: "提高10点敏捷。",
  23: "提高10点智力。",
  24: "全属性+10。",
  25: "提高20点攻击速度。",
  26: "15%吸血。",
  27: "每秒回复5点生命值。",
  28: "每秒回复1.25点魔法值。",
  31: "提高15%魔法抗性。",
  32: "提高16%闪避率。",
  33: "使用后回复2500点生命值和1500点魔法值。",
  34: "获得充能后使用，每点充能回复15点生命和魔法。附近有敌人施放技能时获得充能，最多10点。",
  36: "获得充能后使用，每点充能回复15点生命和魔法。最多20点。全属性+4。",
  37: "使用后进入虚化状态，免疫物理攻击但受到额外魔法伤害。",
  38: "使用后恢复150点魔法值。受到攻击会打断。",
  39: "使用后回复400点生命值。受到攻击会打断。",
  40: "使用后在周围区域揭示隐形单位和守卫。",
  41: "在河道获得神符时自动储存。使用后回复生命和魔法。可使用3次。",
  42: "放置一个侦查守卫，持续6分钟，提供800范围的视野。",
  43: "放置一个岗哨守卫，持续8分钟，能发现隐形单位和守卫。",
  44: "使用时选中一棵树，吞食后获得持续治疗。可食用3次。",
  46: "使用后经过3秒施法，传送至友方建筑或单位。",
  48: "移动速度+110。可传送至任何友方非英雄单位或建筑（80秒CD）。",
  50: "移动速度+50，攻击力+18。使用后获得相位状态，无视单位碰撞并提高移动速度。",
  63: "移动速度+50，攻击速度+30。可切换属性：力量+10/敏捷+10/智力+10。",
  65: "攻击速度+45。主动对非英雄单位使用，立即击杀并获得200金币。",
  69: "生命恢复+7，魔法恢复+4。",
  73: "力量+6，敏捷+3，智力+3，攻击力+10。",
  75: "敏捷+6，力量+3，智力+3，攻击力+10。",
  77: "智力+6，力量+3，敏捷+3，攻击力+10。",
  79: "全属性+4，护甲+8。主动使用回复周围友军275点生命值。",
  81: "提供范围吸血（20%）、攻击力（15%）、魔法恢复（2）和护甲（4）光环。",
  90: "魔法抗性+30%，生命恢复+10。主动使用给周围友方提供魔法护盾（吸收400点魔法伤害）。",
  92: "力量+8，全属性+2。附近英雄死亡时获得充能，可对自己或队友使用回复生命。",
  96: "智力+45，全属性+16。主动使用将目标变成小猪3.5秒。",
  98: "智力+40，攻击力+30，攻击速度+30。主动沉默目标5秒，结束时结算额外30%伤害。",
  100: "智力+10，魔法恢复+5，移动速度+65。主动将目标吹入空中2.5秒。",
  102: "智力+10，生命恢复+5。主动将目标推移600距离（含自身）。",
  104: "智力+21，攻击力+12。主动对目标释放400点魔法伤害。可升级4次，每升1级伤害提高100点。",
  108: "全属性+10，生命+375，魔法+375。提升终极技能效果。",
  110: "生命恢复+14，魔法恢复+12。主动使用刷新所有技能和物品CD（CD 180秒）。",
  112: "攻击速度+30，护甲+15。提供攻速和护甲光环给友方。降低敌方护甲。",
  114: "力量+40，生命恢复+1.6%。脱离战斗后生命恢复大幅提高。",
  116: "攻击力+30，力量+12。使用后获得魔法免疫状态（持续9秒，最低6秒）。",
  117: "肉山掉落。死亡时消耗此物品，立刻在原地满状态复活。",
  119: "智力+30，护甲+15。主动使用对周围敌人造成持续魔法伤害和减速。",
  121: "生命+550，魔法+550。每点充能提供生命恢复和魔法恢复。死亡时回复附近友方。",
  123: "全属性+15，生命恢复+7，魔法恢复+6。每12秒格挡一次指向性法术。",
  125: "生命+250，生命恢复+7，护甲+5。60%概率格挡近战50点/远程25点伤害。",
  127: "攻击力+28，护甲+7，智力+8。激活后反弹受到的伤害（持续4.5秒）。",
  131: "魔法抗性+25%，生命恢复+7。",
  133: "攻击力+350。死亡时掉落，其他英雄可以捡起。",
  135: "攻击力+40，攻击速度+45。普通攻击有80%概率额外造成70点魔法伤害并无视闪避。",
  137: "每秒对周围700范围造成60点魔法伤害。普通攻击使目标暂时丢失15%概率。攻击力+60。",
  139: "敏捷+35，攻击速度+30，护甲+5，闪避+30%。",
  141: "攻击力+81。普通攻击有30%概率造成225%暴击伤害。",
  143: "攻击力+25，力量+10。近战普通攻击有25%概率击晕目标1.5秒。",
  145: "近战攻击对目标周围650范围内敌人造成70%溅射伤害。攻击力+60，生命/魔法恢复+7.5。",
  147: "敏捷+26，闪避+25%，攻击力+12，移动速度+30。主动制造2个幻象。",
  149: "攻击力+42。普通攻击有30%概率造成160%暴击伤害。",
  151: "攻击力+30，力量+10，攻击速度+30，护甲+6。激活后持续消耗生命换来加成。",
  152: "攻击力+25，攻击速度+30。使用后进入隐身状态14秒。破隐一击额外175点伤害。",
  154: "力量+16，敏捷+16，攻击速度+20，移动速度+30，状态抗性+20%。",
  156: "攻击力+30，力量+25，吸血+25%。激活后将吸血提升至180%。",
  158: "攻击力+24，攻击速度+70。普通攻击有30%概率释放连锁闪电。",
  160: "全属性+25，生命+250，魔法+250。普通攻击减速目标。",
  162: "力量+16，减速抗性+15%，生命恢复+5。",
  166: "攻击力+24，攻击速度+25。普通攻击有30%概率释放连锁闪电（120点伤害）。",
  168: "攻击力+60。普通攻击减少目标6点护甲，持续7秒。",
  170: "敏捷+16，攻击速度+15，移速+30。",
  172: "攻击力+30，攻击速度+50，吸血+20%。激活后大幅提高攻速移速。",
  174: "攻击力+15，敏捷+10，智力+10。普通攻击燃烧目标40点魔法值并造成等量物理伤害。",
  176: "智力+50，敏捷+10，力量+10。主动将目标虚化。",
  178: "力量+5，护甲+5。牺牲150点生命换取170点魔法值。",
  180: "移动速度+50。使用后回复周围友方英雄160点魔法值。",
  185: "全属性+8，移速+25。主动释放增加友军攻速和移速。",
  187: "全属性+1，护甲+7。可对友方使用，降低其护甲换取攻击力。",
  188: "使用后使附近友方英雄进入隐身状态，持续35秒。",
  190: "全属性+6，智力+6。主动对范围内敌人施加20%魔法易伤。",
  206: "力量+12，智力+12，生命+200。主动减速目标，2秒后禁锢2.5秒。",
  208: "攻击力+40，生命+250，生命恢复+10。近战有25%概率击晕。主动击晕2秒。",
  210: "力量+25，状态抗性+20%，生命恢复+5，攻击力+20。可主动缴械目标。",
  212: "敏捷+6，智力+3，攻击力+10。提供范围护甲光环。",
  214: "移动速度+65，生命恢复+14。脱离战斗后移速提高至+85。",
  216: "立刻回复100点魔法值。",
  218: "放置一个侦查与岗哨兼顾的守卫，提供视野并能发现隐形单位。",
  220: "移动速度+130。可传送至任何友方英雄、单位或建筑（40秒CD）。",
  223: "智力+12，生命恢复+3，魔法恢复+2。引导后召唤陨石，造成眩晕和伤害。",
  225: "攻击力+75，护甲+10，生命恢复+6。主动解除目标的附魔效果并使其减速。",
  226: "护甲+10，生命恢复+7，魔法恢复+6。可以对友方使用驱散并短时间免疫。",
  229: "全属性+8，护甲+8。主动给友方提供高额护甲和攻击速度加成。",
  231: "移动速度+50，全属性+5，护甲+8。主动回复周围友军400点生命和200点魔法。",
  232: "魔法值+300，魔法恢复+3。提高施法距离250。",
  235: "智力+30，技能冷却减少25%，技能吸血25%。生命+250，魔法+250。",
  236: "力量+14，敏捷+6，攻击距离+150。",
  242: "生命+250，生命恢复+7，护甲+12。主动使用给周围友军提供格挡效果。",
  249: "攻击力+45，攻击速度+30。破隐一击额外250点伤害并无视被动技能。",
  250: "智力+45，攻击力+55，攻击速度+40。主动沉默目标并使后续伤害暴击。",
  252: "攻击力+15，力量+10，智力+10，魔法恢复+2。普通攻击附带减速和额外伤害。",
  254: "智力+8，攻击速度+20。主动使目标隐身并获得额外魔法抗性。",
  256: "生命+300，魔法+300。受到致命伤害时触发，短时间内免疫伤害。",
  259: "智力+16，魔法消耗-10%，技能增强+10%。",
  261: "全属性+4。",
  263: "力量+15，敏捷+15，攻击力+15，攻击距离+150。主动推移目标同时自身后退。",
  267: "力量+12，全属性+4，生命+150。充能效果增强，可对敌方使用造成持续伤害。",
  269: "生命+300，魔法抗性+20%，生命恢复+5。给周围友军提供治疗增强光环。",
  273: "智力+16，敏捷+16，攻击速度+20，移速+30，魔法消耗-20%。",
  277: "力量+16，智力+16，减速抗性+25%，魔法消耗-20%。",
  534: "攻击力+30，智力+12，攻击速度+25。普通攻击附加基于智力的额外魔法伤害。",
  596: "攻击力+25，攻击速度+35，魔法恢复+1.8，全属性+4。",
  600: "力量+25。闪烁落地时对周围敌人造成力量值+100的魔法伤害和减速。",
  603: "敏捷+25。闪烁后获得40%移动速度加成和30攻击速度，持续6秒。",
  604: "智力+25。闪烁后获得30%技能冷却加速和30%魔法消耗降低，持续6秒。",
  610: "智力+30，魔法恢复+5，移动速度+50。可对自己或敌人使用风杖效果。",
  635: "护甲+10，全属性+8，生命恢复+9。支配一个非英雄单位，光环效果提升。",
  692: "智力+15，魔法抗性+30%，生命恢复+7。将部分魔法伤害转化为魔法值。",
  939: "攻击力+30，力量+20，智力+10，生命恢复+7。主动使用将目标拉至面前。",
  911: "智力+30，攻击速度+35，攻击力+25。可切换为无视魔法抗性的魔法伤害。",
  1097: "攻击力+45，敏捷+20，智力+10。普通攻击燃烧目标50点魔法值。可使用分身。",
  1107: "智力+14，生命+150，生命恢复+5。使用技能后下次普通攻击附带150点魔法伤害。",
  1123: "投掷一颗榴弹，对范围内敌人造成持续伤害并减速。",
  1125: "提高5点生命恢复和2点魔法恢复。",
  1128: "全属性+6，提供范围护甲和魔法恢复光环。主动开启格挡伤害。",
  1466: "力量+12，智力+18，生命+250。主动减速目标并召唤锁链禁锢范围内所有敌人。",
  1806: "智力+20，全属性+10，生命+400。主动释放对周围敌人的魔法伤害和治疗友方。",
  1808: "智力+18，生命+200，魔法恢复+3。技能对目标附加额外魔法伤害和减速。",
  1852: "主动使用对友方提供大量治疗，同时对周围敌人造成魔法伤害。",
  1854: "提供高额魔法抗性和生命恢复，主动使用吸收魔法伤害。",
  1856: "智力+20，魔法恢复+3，全属性+4。技能伤害附带减速效果。",
};

const items = JSON.parse(readFileSync(join(__dirname, "items_api.json"), "utf-8"));

const lines = [];
lines.push('import type { ItemData } from "@/types/dota";');
lines.push("");
lines.push("export const MOCK_ITEMS: ItemData[] = [");

function esc(s) {
  if (!s) return "";
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, " ")
    .replace(/\t/g, " ");
}

let count = 0;
for (const [key, val] of Object.entries(items)) {
  if (typeof val !== "object" || !val || !("id" in val)) continue;
  const item = val;
  if (!item.id || !item.dname) continue;

  // Skip recipes and "Upgraded" items that are just aliases
  const name = item.dname;
  if (name.startsWith("Recipe:") || name.startsWith("Upgraded:")) continue;

  const imgRaw = item.img || "";
  const imgMatch = imgRaw.match(/\/items\/(.+)\.png/);
  const imgName = imgMatch ? imgMatch[1] : key;

  let zh = chineseNames[key] || chineseNames[imgName] || "";
  if (!zh) {
    // Generic fallback: "X Recipe" → remove Recipe suffix
    if (name.endsWith(" Recipe")) {
      const baseName = name.replace(/ Recipe$/, "");
      zh = chineseNames[baseName.toLowerCase().replace(/\s+/g, "_")] || baseName;
      if (!zh.endsWith("合成卷轴")) zh += "合成卷轴";
    } else {
      zh = name;
    }
  }
  zh = esc(zh);

  let cost = 0;
  if (typeof item.cost === "number" && !Number.isNaN(item.cost) && item.cost > 0 && item.cost < 100000) {
    cost = item.cost;
  } else if (typeof item.cost === "string") {
    cost = parseInt(item.cost) || 0;
  }

  const recipe = itemRecipes[item.id];
  const componentsStr = recipe ? `[${recipe.join(", ")}]` : "[]";
  const desc = itemDescriptions[item.id] || (item.lore || "").substring(0, 80);

  lines.push(`  {`);
  lines.push(`    id: ${item.id},`);
  lines.push(`    name: "item_${key}",`);
  lines.push(`    localizedNameZh: "${zh}",`);
  lines.push(`    localizedNameEn: "${esc(name)}",`);
  lines.push(`    cost: ${cost},`);
  lines.push(`    isRecipe: false,`);
  lines.push(`    isSecretShop: false,`);
  lines.push(`    components: ${componentsStr},`);
  lines.push(`    imageIcon: "${esc(imgName)}",`);
  lines.push(`    descriptionZh: "${esc(desc)}",`);
  lines.push(`    tier: null,`);
  lines.push(`    isActive: true,`);
  lines.push(`  },`);
  count++;
}

lines.push("];");
lines.push("");

const outputPath = join(__dirname, "..", "src", "lib", "data", "items-mock.ts");
writeFileSync(outputPath, lines.join("\n"), "utf-8");
console.log(`Written ${count} items to ${outputPath}`);
