// Generate item mock data from OpenDota API response
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Chinese name mappings for common items
const chineseNames = {
  // ── Consumables ──
  blink: "闪烁匕首",
  tango: "树之祭祀",
  tango_single: "树之祭祀（共享）",
  flask: "治疗药膏",
  healing_salve: "治疗药膏",
  clarity: "净化药水",
  enchanted_mango: "魔法芒果",
  faerie_fire: "仙灵之火",
  blood_grenade: "血榴弹",
  dust: "显影之尘",
  smoke_of_deceit: "诡计之雾",
  town_portal_scroll: "回城卷轴",
  tpscroll: "回城卷轴",
  ward_observer: "侦查守卫",
  ward_sentry: "岗哨守卫",
  sentry_wards: "岗哨守卫",
  ward_dispenser: "侦查·岗哨守卫",
  aegis: "不朽之守护",
  cheese: "奶酪",
  refresher_shard: "刷新球碎片",
  aghanims_shard: "阿哈利姆魔晶",
  aghanims_blessing: "阿哈利姆福佑",
  ultimate_scepter: "阿哈利姆神杖",
  bottle: "魔瓶",
  // ── Basic items (with API key aliases) ──
  branches: "铁树枝干",
  iron_branch: "铁树枝干",
  gauntlets: "力量手套",
  slippers: "敏捷便鞋",
  mantle: "智力斗篷",
  circlet: "贵族圆环",
  belt_of_strength: "力量腰带",
  boots_of_elves: "精灵皮靴",
  robe: "法师长袍",
  ogre_axe: "食人魔之斧",
  blade_of_alacrity: "欢欣之刃",
  staff_of_wizardry: "魔力法杖",
  ring_of_protection: "守护指环",
  ring_of_regen: "治疗指环",
  ring_of_health: "治疗指环",
  sage_mask: "贤者面罩",
  sobi_mask: "贤者面罩",
  boots_of_speed: "速度之靴",
  boots: "速度之靴",
  gloves: "加速手套",
  blades_of_attack: "攻击之爪",
  chainmail: "锁子甲",
  quarterstaff: "短棍",
  helm_of_iron_will: "铁意头盔",
  broadsword: "阔剑",
  claymore: "大剑",
  javelin: "标枪",
  platemail: "板甲",
  hyperstone: "振奋宝石",
  void_stone: "虚无宝石",
  gem: "真视宝石",
  ghost: "幽魂权杖",
  shadow_amulet: "暗影护符",
  morbid_mask: "吸血面具",
  lifesteal: "吸血面具",
  voodoo_mask: "巫毒面具",
  fluffy_hat: "毛帽",
  wind_lace: "风灵之纹",
  cloak: "抗魔斗篷",
  talisman_of_evasion: "闪避护符",
  blitz_knuckles: "闪电指套",
  ultimate_orb: "极限法球",
  stout_shield: "圆盾",
  poor_mans_shield: "穷鬼盾",
  ring_of_aquila: "天鹰之戒",
  quelling_blade: "压制之斧",
  orb_of_venom: "淬毒之珠",
  infused_raindrop: "凝魂之露",
  magic_stick: "魔棒",
  magic_wand: "魔杖",
  soul_ring: "灵魂之戒",
  crown: "王冠",
  diadem: "王冠",
  mithril_hammer: "秘银锤",
  reaver: "掠夺者之斧",
  eagle: "鹰歌弓",
  eaglesong: "鹰歌弓",
  mystic_staff: "神秘法杖",
  demon_edge: "恶魔刀锋",
  relic: "圣者遗物",
  sacred_relic: "圣者遗物",
  ring_of_tarrasque: "恐鳌之戒",
  energy_booster: "能量之球",
  point_booster: "精气之球",
  vitality_booster: "活力之球",
  soul_booster: "灵魂之球",
  tiara_of_selemene: "瑟勒梅涅之冠",
  wizard_hat: "巫师之帽",
  diffusal_blade: "净魂之刃",
  diffusal_blade_2: "净魂之刃",
  // ── Boots ──
  power_treads: "动力鞋",
  phase_boots: "相位鞋",
  arcane_boots: "奥术鞋",
  tranquil_boots: "静谧之靴",
  boots_of_travel: "远行鞋",
  travel_boots: "远行鞋",
  travel_boots_2: "远行鞋II",
  guardian_greaves: "卫士胫甲",
  boots_of_bearing: "统御头盔",
  force_boots: "原力鞋",
  swift_boots: "迅捷之靴",
  // API key aliases for items with non-standard keys
  invis_sword: "影刃",
  bfury: "狂战斧",
  lesser_crit: "水晶剑",
  greater_crit: "代达罗斯之殇",
  gungir: "缚灵索",
  sheepstick: "邪恶镰刀",
  scythe_of_vyse: "邪恶镰刀",
  cyclone: "EUL的神圣法杖",
  euls: "EUL的神圣法杖",
  ancient_janggo: "韧鼓",
  pers: "坚韧球",
  perseverance: "坚韧球",
  oblivion_staff: "遗忘法杖",
  angels_demise: "天命",
  khanda: "天命",
  aether_lens: "以太透镜",
  blight_stone: "枯萎之石",
  orb_of_blight: "枯萎之石",
  orb_of_frost: "冰霜之球",
  orb_of_corrosion: "腐蚀之珠",
  devastator: "圣契",
  parasma: "圣契",
  dagon_2: "达贡之神力",
  dagon_3: "达贡之神力",
  dagon_4: "达贡之神力",
  dagon_5: "达贡之神力",
  necronomicon: "死灵书",
  necronomicon_2: "死灵书",
  necronomicon_3: "死灵书",
  ultimate_scepter_2: "阿哈利姆福佑",
  ultimate_scepter_roshan: "阿哈利姆福佑（肉山）",
  aghanims_blessing: "阿哈利姆福佑",
  mekansm: "梅肯斯姆",
  wraith_pact: "冥魂盟约",
  headdress: "头巾",
  recipe_cyclone: "EUL神圣法杖合成卷轴",
  // ── Early / Mid game items ──
  bracer: "护腕",
  wraith_band: "幽灵系带",
  null_talisman: "空灵挂件",
  falcon_blade: "猎鹰战刃",
  hand_of_midas: "迈达斯之手",
  mask_of_madness: "疯狂面具",
  battle_fury: "狂战斧",
  desolator: "黯灭",
  maelstrom: "漩涡",
  mjollnir: "雷神之锤",
  crystalys: "水晶剑",
  daedalus: "代达罗斯之殇",
  basher: "碎颅锤",
  abyssal_blade: "深渊之刃",
  radiance: "辉耀",
  butterfly: "蝴蝶",
  satanic: "撒旦之邪力",
  skadi: "斯嘉蒂之眼",
  monkey_king_bar: "金箍棒",
  divine_rapier: "圣剑",
  rapier: "圣剑",
  moon_shard: "银月之晶",
  manta: "幻影斧",
  black_king_bar: "黑皇杖",
  silver_edge: "白银之锋",
  shadow_blade: "影刃",
  echo_sabre: "回音战刃",
  harpoon: "鱼叉",
  nullifier: "否决坠饰",
  disperser: "分散机",
  diffusal_blade: "净魂之刃",
  ethereal_blade: "虚灵之刃",
  dagon: "达贡之神力",
  orchid: "紫怨",
  bloodthorn: "血棘",
  mage_slayer: "巫师之刃",
  witch_blade: "巫师之刃",
  revenants_brooch: "亡魂胸针",
  parasma: "圣契",
  gleipnir: "缚灵索",
  rod_of_atos: "阿托斯之棍",
  dragon_lance: "魔龙枪",
  hurricane_pike: "飓风长戟",
  meteor_hammer: "陨星锤",
  phylactery: "灵匣",
  khanda: "天命",
  armlet: "莫尔迪基安的臂章",
  armlet_of_mordiggian: "莫尔迪基安的臂章",
  // ── Defensive / Utility ──
  hood_of_defiance: "挑战头巾",
  pipe: "洞察烟斗",
  pipe_of_insight: "洞察烟斗",
  eternal_shroud: "永世法衣",
  vanguard: "先锋盾",
  crimson_guard: "赤红甲",
  blade_mail: "刃甲",
  heart: "恐鳌之心",
  tarrasque: "恐鳌之心",
  assault: "强袭胸甲",
  assault_cuirass: "强袭胸甲",
  shivas_guard: "希瓦的守护",
  lotus_orb: "清莲宝珠",
  sphere: "林肯法球",
  linkens_sphere: "林肯法球",
  bloodstone: "血精石",
  aeon_disk: "永恒之盘",
  force_staff: "原力法杖",
  glimmer_cape: "微光披风",
  holy_locket: "圣洁吊坠",
  mekanism: "梅肯斯姆",
  buckler: "圆盾",
  ring_of_basilius: "圣殿指环",
  heavens_halberd: "天堂之戟",
  solar_crest: "炎阳纹章",
  medallion_of_courage: "勇气勋章",
  urn_of_shadows: "影之灵龛",
  spirit_vessel: "魂之灵龛",
  drum_of_endurance: "韧鼓",
  veil_of_discord: "纷争面纱",
  helm_of_the_dominator: "支配头盔",
  helm_of_the_overlord: "统御头盔",
  vladmir: "弗拉迪米尔的祭品",
  ghost_scepter: "幽魂权杖",
  euls: "EUL的神圣法杖",
  wind_waker: "风之杖",
  scythe_of_vyse: "邪恶镰刀",
  octarine_core: "玲珑心",
  refresher: "刷新球",
  overwhelming_blink: "蛮牛闪现",
  swift_blink: "迅捷闪现",
  arcane_blink: "奥术闪现",
  kaya: "慧光",
  yasha: "夜叉",
  sange: "散华",
  kaya_and_sange: "慧夜对剑",
  yasha_and_kaya: "散慧对剑",
  sange_and_yasha: "散夜对剑",
  trident: "三叉戟",
  // ── New 7.41 items ──
  splintmail: "裂片甲",
  shawl: "披肩",
  chasm_stone: "深渊石",
  essence_distiller: "精华蒸馏器",
  consecrated_wraps: "圣洁裹布",
  crellas_crozier: "克莱拉主教权杖",
  eldwurms_edda: "埃尔德武姆史诗",
  pavise: "圣盾",
  // ── Neutral items (common) ──
  arcane_ring: "奥术指环",
  trusty_shovel: "可靠铁铲",
  paladin_sword: "圣骑士剑",
  dragon_scale: "龙鳞",
  spider_legs: "蜘蛛腿",
  vambrace: "臂甲",
  titan_sliver: "泰坦碎片",
  mind_breaker: "碎心刃",
  stormcrafter: "风暴工匠",
  elven_tunic: "精灵外衣",
  penta_edged_sword: "五锋剑",
  stygian_desolator: "冥灵黯灭",
  prism: "棱镜",
  mechanical_arm: "机械臂",
  enchanted_quiver: "附魔箭袋",
  specialists_array: "专家阵列",
  dagger_of_ristul: "利斯塔匕首",
  orb_of_destruction: "毁灭之球",
  bullwhip: "牛鞭",
  phoenix_ash: "凤凰灰烬",
  possessed_mask: "着魔面具",
  trickster_cloak: "诡计披风",
  ninja_gear: "忍者装备",
  illusionsts_cape: "幻术师披风",
  blighted_spirit: "枯萎之灵",
  timeless_relic: "永恒遗物",
  psychic_headband: "灵心头带",
  book_of_shadows: "暗影之书",
  book_of_the_dead: "亡灵之书",
  force_boots: "原力鞋",
  fallen_sky: "陨落天空",
  philosophers_stone: "贤者之石",
  eye_of_the_vizier: "维齐尔之眼",
  orb_of_corrosion: "腐蚀之珠",
  grandmasters_glaive: "宗师长刃",
  flicker: "闪烁",
  seer_stone: "先见之石",
  bottomless_chalice: "无尽圣杯",
  wand_of_the_brine: "盐水之杖",
  whisper_of_the_dread: "恐惧低语",
  bone_golem: "骨傀儡",
  super_blink: "超级闪烁",
  giant_ring: "巨人之戒",
  apex: "巅峰",
  ballista: "弩炮",
  woodland_striders: "林地行者",
  mirror_shield: "镜盾",
  ex_machina: "机械降神",
  book_of_the_dead_2: "亡灵之书",
  pirate_hat: "海盗帽",
  fairy_treasure: "仙灵宝藏",
  magic_jewel: "魔法宝石",
  flaming_scythe: "火焰镰刀",
  glowcap: "萤光菇",
  forebearer: "先祖",
  red_orb: "红球",
  shrink_ray: "缩小射线",
  satchel: "背包",
  // ── Tokens / Consumable neutral items ──
  tier_1_token: "一级中立代币",
  tier_2_token: "二级中立代币",
  tier_3_token: "三级中立代币",
  tier_4_token: "四级中立代币",
  tier_5_token: "五级中立代币",
  // ── Misc / Removed / Seasonal ──
  courier: "动物信使",
  flying_courier: "飞行信使",
  tome_of_knowledge: "知识之书",
  royal_jelly: "皇家蜂蜜",
  mango_tree: "芒果果树",
  repair_kit: "修理包",
  iron_talon: "铁爪",
  // ── Recipes ──
  recipe: "合成卷轴",
  recipe_arcane_blink: "奥术闪现合成卷轴",
  recipe_swift_blink: "迅捷闪现合成卷轴",
  recipe_overwhelming_blink: "蛮牛闪现合成卷轴",
  recipe_magic_wand: "魔杖合成卷轴",
  recipe_travel_boots: "远行鞋合成卷轴",
  recipe_mekansm: "梅肯斯姆合成卷轴",
  recipe_buckler: "圆盾合成卷轴",
  recipe_ring_of_basilius: "圣殿指环合成卷轴",
  recipe_holy_locket: "圣洁吊坠合成卷轴",
  recipe_pipe: "洞察烟斗合成卷轴",
  recipe_urn_of_shadows: "影之灵龛合成卷轴",
  recipe_headdress: "头巾合成卷轴",
  recipe_scythe_of_vyse: "邪恶镰刀合成卷轴",
  recipe_orchid: "紫怨合成卷轴",
  recipe_bloodthorn: "血棘合成卷轴",
  recipe_euls: "EUL神圣法杖合成卷轴",
  recipe_wind_waker: "风之杖合成卷轴",
  recipe_aether_lens: "以太透镜合成卷轴",
  recipe_force_staff: "原力法杖合成卷轴",
  recipe_hurricane_pike: "飓风长戟合成卷轴",
  recipe_dagon: "达贡之神力合成卷轴",
  recipe_aghanims_blessing: "阿哈利姆福佑合成卷轴",
  recipe_refresher: "刷新球合成卷轴",
  recipe_assault: "强袭胸甲合成卷轴",
  recipe_heart: "恐鳌之心合成卷轴",
  recipe_black_king_bar: "黑皇杖合成卷轴",
  recipe_shivas_guard: "希瓦守护合成卷轴",
  recipe_sphere: "林肯法球合成卷轴",
  recipe_lotus_orb: "清莲宝珠合成卷轴",
  recipe_meteor_hammer: "陨星锤合成卷轴",
  recipe_aeon_disk: "永恒之盘合成卷轴",
  recipe_kaya: "慧光合成卷轴",
  recipe_spirit_vessel: "魂之灵龛合成卷轴",
  recipe_essence_distiller: "精华蒸馏器合成卷轴",
  recipe_crimson_guard: "赤红甲合成卷轴",
  recipe_blade_mail: "刃甲合成卷轴",
  recipe_eternal_shroud: "永世法衣合成卷轴",
  recipe_consecrated_wraps: "圣洁裹布合成卷轴",
  recipe_crellas_crozier: "克莱拉权杖合成卷轴",
  recipe_monkey_king_bar: "金箍棒合成卷轴",
  recipe_daedalus: "代达罗斯之殇合成卷轴",
  recipe_basher: "碎颅锤合成卷轴",
  recipe_battle_fury: "狂战斧合成卷轴",
  recipe_manta: "幻影斧合成卷轴",
  recipe_crystalys: "水晶剑合成卷轴",
  recipe_dragon_lance: "魔龙枪合成卷轴",
  recipe_armlet: "臂章合成卷轴",
  recipe_silver_edge: "白银之锋合成卷轴",
  recipe_mjollnir: "雷神之锤合成卷轴",
  recipe_sange: "散华合成卷轴",
  recipe_helm_of_the_dominator: "支配头盔合成卷轴",
  recipe_helm_of_the_overlord: "统御头盔合成卷轴",
  recipe_gleipnir: "缚灵索合成卷轴",
  recipe_yasha: "夜叉合成卷轴",
  recipe_diffusal_blade: "净魂之刃合成卷轴",
  recipe_disperser: "分散机合成卷轴",
  recipe_ethereal_blade: "虚灵之刃合成卷轴",
  recipe_soul_ring: "灵魂之戒合成卷轴",
  recipe_arcane_boots: "奥术鞋合成卷轴",
  recipe_octarine_core: "玲珑心合成卷轴",
  recipe_falcon_blade: "猎鹰战刃合成卷轴",
  recipe_drum: "韧鼓合成卷轴",
  recipe_solar_crest: "炎阳纹章合成卷轴",
  recipe_pavise: "圣盾合成卷轴",
  recipe_veil: "纷争面纱合成卷轴",
  recipe_revenants_brooch: "亡魂胸针合成卷轴",
  recipe_parasma: "圣契合卷轴",
  recipe_guardian_greaves: "卫士胫甲合成卷轴",
  recipe_rod_of_atos: "阿托斯之棍合成卷轴",
  recipe_iron_talon: "铁爪合成卷轴",
  recipe_abyssal_blade: "深渊之刃合成卷轴",
  recipe_heavens_halberd: "天堂之戟合成卷轴",
  recipe_glimmer_cape: "微光披风合成卷轴",
  recipe_harpoon: "鱼叉合成卷轴",
  recipe_bracer: "护腕合成卷轴",
  recipe_wraith_band: "幽灵系带合成卷轴",
  recipe_null_talisman: "空灵挂件合成卷轴",
  recipe_witch_blade: "巫师之刃合成卷轴",
  recipe_phylactery: "灵匣合成卷轴",
  recipe_khanda: "天命合成卷轴",
  // ── Neutral items newer ──
  vengeances_shadow: "复仇之影",
  stygian_desolator: "冥灵黯灭",
  desolator_2: "黯灭II",
  seer_stone_2: "先见之石II",
  warhammer: "战锤",
  stinger: "毒刺",
  demonedge: "恶魔之刃",
  armor_greaves: "装甲胫甲",
  ancient_persuasion: "远古说服",
  soul_stealing_mask: "噬魂面具",
  fairy_trinket: "仙灵饰物",
  chipped_vest: "破碎背心",
  ocean_heart: "海洋之心",
  broom_handle: "扫帚柄",
  nether_shawl: "冥界披肩",
  essence_ring: "精华指环",
  clumsy_net: "笨拙捕网",
  havoc_hammer: "浩劫之锤",
  magic_lamp: "魔法神灯",
  faded_broach: "褪色胸针",
  minotaur_horn: "牛头人号角",
  the_leveller: "平整者",
  cloak_of_flames: "火焰斗篷",
  ceremonial_robe: "仪式长袍",
  quicksilver_amulet: "水银护符",
  giants_ring: "巨人之戒",
  fairys_trinket: "仙灵饰物",
  ascetics_cap: "苦行者之帽",
  brigands_blade: "强盗之刃",
  witchbane: "破法之刃",
  pig_pole: "猪竿",
  tumblers_toy: "不倒翁玩具",
  fae_grenade: "仙灵手雷",
  seeds_of_serenity: "宁静种子",
  lance_of_pursuit: "追猎长矛",
  occult_bracelet: "神秘手镯",
  ogre_seal_totem: "食人魔海豹图腾",
  defiant_shell: "抗争之壳",
  beloved_memory: "挚爱回忆",
  scrying_shovel: "占卜铲",
  forebearers_fortune: "先祖馈赠",
  mercy_and_grace: "慈悲与恩典",
  vindicators_axe: "复仇者之斧",
  duelist_gloves: "决斗者手套",
  ancient_guardian: "远古守护者",
  safety_bubble: "安全气泡",
  nemesis_curse: "复仇诅咒",
  avianas_feather: "艾维娜之羽",
  unwavering_condition: "坚定状态",
  dandelion_amulet: "蒲公英护符",
  martyrs_plate: "殉道者板甲",
  gossamer_cape: "薄纱披风",
  light_collector: "光之收集者",
  rattlecage: "震响之笼",
  doubloon: "达布隆金币",
  roshans_banner: "肉山旗帜",
  unrelenting_eye: "无情之眼",
  mana_draught: "法力药剂",
  rippers_lash: "撕裂者之鞭",
  crippling_crossbow: "致残弩",
  gale_guard: "狂风护甲",
  gunpowder_gauntlet: "火药护手",
  searing_signet: "灼热印记",
  serrated_shiv: "锯齿小刀",
  pollywog_charm: "蝌蚪护符",
  magnifying_monocle: "放大镜",
  pyrrhic_cloak: "惨胜披风",
  madstone_bundle: "狂石包裹",
  kobold_cup: "狗头人酒杯",
  dormant_curio: "休眠古玩",
  sisters_shroud: "姐妹裹尸布",
  jidi_pollen_bag: "吉迪花粉袋",
  outworld_staff: "异界法杖",
  dezun_bloodrite: "德尊血仪",
  giants_maul: "巨人之槌",
  divine_regalia: "神圣王权",
  disgraced_regalia: "耻辱王权",
  bag_of_gold: "金币袋",
  hydras_breath: "多头蛇吐息",
  weighted_dice: "灌铅骰子",
  ash_legion_shield: "灰烬军团之盾",
  riftshadow_prism: "裂影棱镜",
  metamorphic_mandible: "变形之颚",
  idol_of_screeauk: "斯克里奥克偶像",
  flayers_bota: "剥皮者之靴",
  spellslinger: "法术投掷者",
  prophets_pendulum: "先知摆锤",
  stonefeather_satchel: "石羽背包",
  enchanters_bauble: "附魔师玩物",
  harmonizer: "协调者",
  conjurers_catalyst: "魔术师催化剂",
  foragers_kit: "采集者工具包",
  vital_toadstool: "活力毒菌",
  ironwood_nut: "铁木坚果",
  tomokan_ringcap: "托莫坎环盖",
  partisans_brand: "游击者烙印",
  leviathans_fish: "利维坦之鱼",
  // ── Level-up runes for heroes ──
  black_grimoire: "黑暗魔典",
  gris_gris: "格里斯护符",
  vast: "巨大",
  quickened: "迅捷",
  audacious: "无畏",
  mystical: "神秘",
  alert: "警觉",
  brawny: "强壮",
  tough: "坚韧",
  feverish: "狂热",
  fleetfooted: "疾步",
  crude: "粗糙",
  boundless: "无限",
  wise: "智慧",
  timeless: "永恒",
  greedy: "贪婪",
  vampiric: "吸血",
  keen_eyed: "敏锐",
  evolved: "进化",
  titanic: "泰坦",
  fierce: "凶猛",
  dominant: "支配",
  restorative: "恢复",
  thick: "厚重",
  unleashed: "释放",
  vital: "活力",
  hulking: "巨硕",
  manic: "狂躁",
  nimble: "灵活",
  // ── Healing lotuses & misc ──
  famango: "治疗莲花",
  great_famango: "大型治疗莲花",
  greater_famango: "超级治疗莲花",
  royale_with_cheese: "奶酪块",
  river_vial_chrome: "河水药瓶：铬",
  river_vial_dry: "河水药瓶：干涸",
  river_vial_slime: "河水药瓶：粘液",
  river_vial_oil: "河水药瓶：油",
  river_vial_electrified: "河水药瓶：电化",
  river_vial_potion: "河水药瓶：药剂",
  river_vial_blood: "河水药瓶：血",
  tombstone: "墓碑",
  pocket_tower: "袖珍塔",
  pocket_roshan: "袖珍肉山",
  keen_optic: "锐利之眼",
  grove_bow: "丛林之弓",
  quickening_charm: "加速护符",
  elixir: "灵药",
  vampire_fangs: "吸血鬼獠牙",
  arcanists_armor: "奥术师铠甲",
  blast_rig: "爆破装置",
  craggy_coat: "崎岖外衣",
  greater_faerie_fire: "大型仙灵之火",
  mirror_shield: "镜盾",
  ironwood_tree: "铁木之树",
  pupil_gift: "学徒的馈赠",
  tome_of_aghanim: "阿哈利姆之书",
  third_eye: "第三只眼",
  spell_prism: "法术棱镜",
  princes_knife: "王子之刃",
  witless_shako: "愚者之帽",
  imp_claw: "小鬼之爪",
  telescope: "望远镜",
  helm_of_the_undying: "不朽之盔",
  fusion_rune: "融合符文",
  ocean_heart: "海洋之心",
  spark_of_courage: "勇气火花",
  nether_shawl: "冥界披肩",
  // ── API key aliases (raw API keys → Chinese) ──
  river_painter: "河水药瓶：铬",
  river_painter2: "河水药瓶：干涸",
  river_painter3: "河水药瓶：粘液",
  river_painter4: "河水药瓶：油",
  river_painter5: "河水药瓶：电化",
  river_painter6: "河水药瓶：药剂",
  river_painter7: "河水药瓶：血",
  mutation_tombstone: "墓碑",
  elixer: "灵药",
  black_powder_bag: "爆破装置",
  spy_gadget: "望远镜",
  panic_button: "魔法神灯",
  demonicon: "亡灵之书",
  mysterious_hat: "仙灵饰物",
  heavy_blade: "破法之刃",
  unstable_wand: "猪竿",
  pogo_stick: "不倒翁玩具",
  paintball: "仙灵手雷",
  ofrenda: "挚爱回忆",
  ofrenda_shovel: "占卜铲",
  ofrenda_pledge: "先祖馈赠",
  muertas_gun: "慈悲与恩典",
  gunpowder_gauntlets: "火药护手",
  polliwog_charm: "蝌蚪护符",
  divine_regalia_broken: "耻辱王权",
  furion_gold_bag: "金币袋",
  foragers_health: "活力毒菌",
  foragers_stats: "铁木坚果",
  foragers_mana: "托莫坎环盖",
  tier1_token: "一级中立代币",
  tier2_token: "二级中立代币",
  tier3_token: "三级中立代币",
  tier4_token: "四级中立代币",
  tier5_token: "五级中立代币",
  grisgris: "格里斯护符",
  enhancement_vast: "巨大",
  enhancement_quickened: "迅捷",
  enhancement_audacious: "无畏",
  enhancement_mystical: "神秘",
  enhancement_alert: "警觉",
  enhancement_brawny: "强壮",
  enhancement_tough: "坚韧",
  enhancement_feverish: "狂热",
  enhancement_fleetfooted: "疾步",
  enhancement_crude: "粗糙",
  enhancement_boundless: "无限",
  enhancement_wise: "智慧",
  enhancement_timeless: "永恒",
  enhancement_greedy: "贪婪",
  enhancement_vampiric: "吸血",
  enhancement_keen_eyed: "敏锐",
  enhancement_evolved: "进化",
  enhancement_titanic: "泰坦",
  enhancement_fierce: "凶猛",
  enhancement_dominant: "支配",
  enhancement_restorative: "恢复",
  enhancement_thick: "厚重",
  enhancement_curious: "释放",
  enhancement_vital: "活力",
  enhancement_hulking: "巨硕",
  enhancement_manic: "狂躁",
  enhancement_nimble: "灵活",
  giants_maul: "巨人之槌",
  tidehunter_fish: "利维坦之鱼",
  aghanims_shard_roshan: "阿哈利姆魔晶（消耗品）",
  force_field: "奥术师铠甲",
  pupils_gift: "学徒的馈赠",
  ascetic_cap: "苦行者之帽",
  misericorde: "强盗之刃",
  giant_maul: "巨人之槌",
  cornucopia: "丰饶之角",
  orb_of_blight: "枯萎之球",
  orb_of_frost: "冰霜之球",
  perseverance: "坚韧球",
};

const items = JSON.parse(readFileSync(join(__dirname, "items_api.json"), "utf-8"));

const lines = [];
lines.push('import type { ItemData } from "@/types/dota";');
lines.push("");
lines.push("export const MOCK_ITEMS: ItemData[] = [");

function esc(s) {
  if (!s) return "";
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, " ")
    .replace(/\t/g, " ");
}

let count = 0;
for (const [key, val] of Object.entries(items)) {
  if (typeof val !== "object" || !val || !("id" in val)) continue;
  const item = val;
  if (!item.id || !item.dname) continue;

  // Skip recipes and "Upgraded" items that are just aliases
  const name = item.dname;
  if (name.startsWith("Recipe:") || name.startsWith("Upgraded:")) continue;

  const imgRaw = item.img || "";
  const imgMatch = imgRaw.match(/\/items\/(.+)\.png/);
  const imgName = imgMatch ? imgMatch[1] : key;

  let zh = chineseNames[key] || chineseNames[imgName] || "";
  if (!zh) {
    // Generic fallback: "X Recipe" → remove Recipe suffix
    if (name.endsWith(" Recipe")) {
      const baseName = name.replace(/ Recipe$/, "");
      zh = chineseNames[baseName.toLowerCase().replace(/\s+/g, "_")] || baseName;
      if (!zh.endsWith("合成卷轴")) zh += "合成卷轴";
    } else {
      zh = name;
    }
  }
  zh = esc(zh);

  let cost = 0;
  if (typeof item.cost === "number" && !Number.isNaN(item.cost) && item.cost > 0 && item.cost < 100000) {
    cost = item.cost;
  } else if (typeof item.cost === "string") {
    cost = parseInt(item.cost) || 0;
  }

  lines.push(`  {`);
  lines.push(`    id: ${item.id},`);
  lines.push(`    name: "item_${key}",`);
  lines.push(`    localizedNameZh: "${zh}",`);
  lines.push(`    localizedNameEn: "${esc(name)}",`);
  lines.push(`    cost: ${cost},`);
  lines.push(`    isRecipe: false,`);
  lines.push(`    isSecretShop: false,`);
  lines.push(`    components: [],`);
  lines.push(`    imageIcon: "${esc(imgName)}",`);
  lines.push(`    descriptionZh: "${esc((item.lore || "").substring(0, 80))}",`);
  lines.push(`    tier: null,`);
  lines.push(`    isActive: true,`);
  lines.push(`  },`);
  count++;
}

lines.push("];");
lines.push("");

const outputPath = join(__dirname, "..", "src", "lib", "data", "items-mock.ts");
writeFileSync(outputPath, lines.join("\n"), "utf-8");
console.log(`Written ${count} items to ${outputPath}`);
